In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/dataset/dataset.csv')
df.head()

,timestamp,cpu_usage,memory_usage,temperature,battery_level,battery_drain,battery_charging,upload_speed_kbps,download_speed_kbps,screen_on,brightness
0,2026-03-09 00:18:05,60,63,36.8,74,-223.0,0,0.000000,0.000000,1,21
1,2026-03-09 00:18:09,49,64,36.8,74,-700.0,0,4.524958,1.739434,1,21
2,2026-03-09 00:18:13,60,67,36.8,74,-417.0,0,0.000000,0.000000,1,21
3,2026-03-09 00:18:17,65,67,36.4,73,-436.0,0,0.394765,0.768830,1,21
4,2026-03-09 00:18:21,52,67,36.4,73,-320.0,0,0.401153,0.540071,1,21

In [3]:
df['timestamp'] = pd.to_datetime(df['timestamp'])
df = df.sort_values("timestamp")

In [4]:
df = df.set_index("timestamp")

In [5]:
df_4s = df.resample("4s").mean()
df_4s = df_4s.ffill()
df_4s = df_4s.interpolate()
df_4s = df_4s.reset_index()

In [6]:
df_4s.head()

,timestamp,cpu_usage,memory_usage,temperature,battery_level,battery_drain,battery_charging,upload_speed_kbps,download_speed_kbps,screen_on,brightness
0,2026-03-09 00:18:04,60.0,63.0,36.8,74.0,-223.0,0.0,0.000000,0.000000,1.0,21.0
1,2026-03-09 00:18:08,49.0,64.0,36.8,74.0,-700.0,0.0,4.524958,1.739434,1.0,21.0
2,2026-03-09 00:18:12,60.0,67.0,36.8,74.0,-417.0,0.0,0.000000,0.000000,1.0,21.0
3,2026-03-09 00:18:16,65.0,67.0,36.4,73.0,-436.0,0.0,0.394765,0.768830,1.0,21.0
4,2026-03-09 00:18:20,52.0,67.0,36.4,73.0,-320.0,0.0,0.401153,0.540071,1.0,21.0

In [7]:
df_4s.to_csv("../data/dataset/dataset_time_series.csv", index=False)