In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/dataset/dataset_dirty.csv')
df.head()

,timestamp,cpu_usage,memory_usage,temperature,battery_level,battery_drain,battery_charging,upload_speed_kbps,download_speed_kbps,screen_on,brightness
0,2026-03-07 16:24:27,78,67,30.7,36,558.0,1,0.000000,0.000000,1,21
1,2026-03-07 16:24:31,47,67,30.7,36,574.0,1,0.419430,0.194631,1,21
2,2026-03-07 16:24:35,34,67,30.7,36,561.0,1,3.326621,2.047748,1,21
3,2026-03-07 16:24:39,35,67,30.7,36,584.0,1,0.303464,0.226871,1,21
4,2026-03-07 16:24:43,24,67,30.7,36,528.0,1,6.931141,10.233627,1,21

In [3]:
df['timestamp'] = pd.to_datetime(df['timestamp'])
df = df.sort_values("timestamp")

In [4]:
df = df.set_index("timestamp")

In [5]:
df_4s = df.resample("4s").mean()
df_4s = df_4s.ffill()
df_4s = df_4s.interpolate()
df_4s = df_4s.reset_index()

In [6]:
df_4s.head()

,timestamp,cpu_usage,memory_usage,temperature,battery_level,battery_drain,battery_charging,upload_speed_kbps,download_speed_kbps,screen_on,brightness
0,2026-03-07 16:24:24,78.0,67.0,30.7,36.0,558.0,1.0,0.000000,0.000000,1.0,21.0
1,2026-03-07 16:24:28,47.0,67.0,30.7,36.0,574.0,1.0,0.419430,0.194631,1.0,21.0
2,2026-03-07 16:24:32,34.0,67.0,30.7,36.0,561.0,1.0,3.326621,2.047748,1.0,21.0
3,2026-03-07 16:24:36,35.0,67.0,30.7,36.0,584.0,1.0,0.303464,0.226871,1.0,21.0
4,2026-03-07 16:24:40,24.0,67.0,30.7,36.0,528.0,1.0,6.931141,10.233627,1.0,21.0

In [8]:
df_4s.to_csv("../data/dataset/dataset.csv", index=False)